version: '3'

services:

  server-service:
    build: 
      context: ./server
      dockerfile: Dockerfile
    ports:
      - 5000:5000
    volumes:
      - ./server:/server
    depends_on:
      - database-service 

  database-service:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: test-docker

  client-service:
   build:
    context: ./client
    dockerfile: Dockerfile
   depends_on:
    - server-service
   ports:
    - 3000:3000
   stdin_open: true
   volumes:
    - ./client:/client